### ISSUE TITLE
Requests taking too long

### ISSUE THREAD

**Issue by fancyvanilla** [IntegerAlex/netflix-recommendation-system#29]
Great work on the app! After forking it and experimenting with it, I noticed that the cosine matrix is regenerated every time a user requests a recommendation. While I attempted to store it using JSON, the file size turned out to be too large. In light of this, I believe utilizing a cache or a database would be a more efficient solution. Additionally, implementing caching for repeated requests could further optimize performance. Best of luck with the continued development of the app!

**Comment by IntegerAlex** [comment]
> Great work on the app! After forking it and experimenting with it, I noticed that the cosine matrix is regenerated every time a user requests a recommendation. While I attempted to store it using JSON, the file size turned out to be too large. In light of this, I believe utilizing a cache or a database would be a more efficient solution. Additionally, implementing caching for repeated requests could further optimize performance. Best of luck with the continued development of the app!

There are few issues needed to be addressed .
1. The response from the OMDB server is slow and cannot be done in bulk 
2. The SSR needs full data before rendering the template
3. Python is slow , I'm not that in python some fixes are needed .


Solutions
Needs paid IMDB api, will reduce 15sec to probably 8sec .
Fixes in script will occur another 1-2sec .
Well it is deployed on cloud run which is bad as it shuts down after sometime and cold starts generally sucks
